### ISSUE TITLE
Allow __name and __data enum value props to be enumerated?

### ISSUE THREAD

**Issue by Pajn** [pocka/rusted#12]
Do you have a strong reason for making __name and __data of EnumValue be non enumerable?

The reason I ask is that it is currently hard to test a function that returns an enum value, bu making them enumerable would allow this:
```
expect(result).toEqual(Some(42))
```

**Comment by pocka** [comment]
The reason for `enumerable: false` is to make `EnumValue` looks clean*. There is no strong opinion for it.
\* hide internal property from an output of `console.dir`, `JSON.stringify`, etc...

And I've just realized that test case you wrote not works... Thank you!

**Comment by Pajn** [comment]
Thank you for getting at this so extremely quick!
